---
sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - git clone git://github.com/sbesson/omero-test-infra -b 5.5 .omero

script:
  - .omero/docker app

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
